### ISSUE TITLE
http\source\golang里

### ISSUE THREAD

**Issue by acxjdjym** [lllk140/BilibiliSuitBuy#11]
http2_socket_golang/http1_socket_golang 运行时未响应咋整

**Comment by lllk140** [comment]
> http2_socket_golang/http1_socket_golang 运行时未响应咋整

黑在那？如果是黑在那选中窗口回车就行

**Comment by acxjdjym** [comment]
> > http2_socket_golang/http1_socket_golang 运行时未响应咋整
> 
> 黑在那？如果是黑在那选中窗口回车就行

http2那里，Get "https://proxy.golang.org/github.com/lllk140/gh2/@v/v0.0.0-20221026060024-a9b1a64405a9.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by lllk140** [comment]
> > > http2_socket_golang/http1_socket_golang 运行时未响应咋整
> > 
> > 
> > 黑在那？如果是黑在那选中窗口回车就行
> 
> http2那里，Get "https://proxy.golang.org/github.com/lllk140/gh2/@v/v0.0.0-20221026060024-a9b1a64405a9.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

网不好而已👀
