### ISSUE TITLE
mian.py（？

### ISSUE THREAD

**Issue by zhuozhiyongde** [lllk140/BilibiliSuitBuy#13]

**Comment by zhuozhiyongde** [comment]
你的readme.md 给了一句python mian.py😂

**Comment by ReOracle** [comment]
> 你的readme.md 给了一句python mian.py😂

有什么问题吗🤔

**Comment by zhuozhiyongde** [comment]
哦 那看来是我老实人了哈哈哈
昨天看到Github推荐来的，以为是作者笔误了x

**Comment by lllk140** [comment]
才发现写错了😂

**Comment by ReOracle** [comment]
> 

笑了 我现在才发现写错了🤣
看了几遍都没发现哪里不对劲

**Comment by zhuozhiyongde** [comment]
哈哈哈哈 我还以为是我老实人指出来了被故意留下了的梗 我甚至还确认了一下 太具有戏剧性了
