### ISSUE TITLE
延时数字前加负号是不是意味着提前？

### ISSUE THREAD

**Issue by RAINighty** [lllk140/BilibiliSuitBuy#15]

**Comment by RAINighty** [comment]
关闭掉GUI画面，仅保留http1_socket_golang是否也能正常运行？

**Comment by ReOracle** [comment]
> 关闭掉GUI画面，仅保留http1_socket_golang是否也能正常运行？

自己试试呗

**Comment by lllk140** [comment]
负号不是提前启动的意思， -1的主要意思是现在启动的时候会把开始时间改成当前时间加30秒，如果想提前启动可以让装扮的开售时间减一，在延时那写950，这意思就是提前50ms启动

**Comment by lllk140** [comment]
负号不是提前启动的意思， -1的主要意思是现在启动的时候会把开始时间改成当前时间加30秒，如果想提前启动可以让装扮的开售时间减一，在延时那写950，这意思就是提前50ms启动

**Comment by lllk140** [comment]
> 关闭掉GUI画面，仅保留http1_socket_golang是否也能正常运行？

能，http里的东西都可单独启动

**Comment by RAINighty** [comment]
> > 关闭掉GUI画面，仅保留http1_socket_golang是否也能正常运行？
> 
> 能，http里的东西都可单独启动

感谢回答
