### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by dfdfd8499** [lllk140/BilibiliSuitBuy#16]
在运行http.bat的时候，显示
install golang-http
go: downloading github.com/lllk140/gh2 v0.0.0-20221026060024-a9b1a64405a9
go: downloading golang.org/x/net v0.1.0
http2_socket_golang.go:7:2: github.com/lllk140/gh2@v0.0.0-20221026060024-a9b1a64405a9: Get "https://proxy.golang.org/github.com/lllk140/gh2/@v/v0.0.0-20221026060024-a9b1a64405a9.zip": dial tcp 172.217.160.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
http2_socket_golang.go:8:2: golang.org/x/net@v0.1.0: Get "https://proxy.golang.org/golang.org/x/net/@v/v0.1.0.zip": dial tcp 172.217.160.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
移动了         1 个文件。
系统找不到指定的文件。
这里超时了，但是可以手动下载。请问怎么解决？非常感谢！

**Comment by lllk140** [comment]
> 在运行http.bat的时候，显示 install golang-http go: downloading github.com/lllk140/gh2 v0.0.0-20221026060024-a9b1a64405a9 go: downloading golang.org/x/net v0.1.0 http2_socket_golang.go:7:2: github.com/lllk140/gh2@v0.0.0-20221026060024-a9b1a64405a9: Get "https://proxy.golang.org/github.com/lllk140/gh2/@v/v0.0.0-20221026060024-a9b1a64405a9.zip": dial tcp 172.217.160.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. http2_socket_golang.go:8:2: golang.org/x/net@v0.1.0: Get "https://proxy.golang.org/golang.org/x/net/@v/v0.1.0.zip": dial tcp 172.217.160.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 移动了 1 个文件。 系统找不到指定的文件。 这里超时了，但是可以手动下载。请问怎么解决？非常感谢！

换成国内源

go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn,direct
