### ISSUE TITLE
请问下整点测试是啥

### ISSUE THREAD

**Issue by gggssepgf** [lllk140/BilibiliSuitBuy#18]
大佬你说去话题问，我也不造话题是啥（

**Comment by lllk140** [comment]
> 大佬你说去话题问，我也不造话题是啥（

整点测试就是找个已经开售的装扮，不用充钱，掐整点去买，能下单就大概率没问题，不能下单这号百分百寄

**Comment by gggssepgf** [comment]
> >

懂了，感谢大佬
