### ISSUE TITLE
code 26134

### ISSUE THREAD

**Issue by ASOUL-D1ana** [lllk140/BilibiliSuitBuy#4]
试了一下 提示26134 购买人数过多
但是我看到最后一次操作的时间戳是1656154799 也就是6:59:59 但是装扮7:00才开始售卖 请问跟这个有原因吗？ 如果是的话是要更改Waitservertimeandstart函数里的sleep(0.02)还是？

**Comment by lllk140** [comment]
控制台只打印到1656154799是因为时间一到就直接运行购买，不经过print。26134是锁号或者锁设备，如果是未开售，返回是26125 商品不存在

**Comment by ASOUL-D1ana** [comment]
好的 谢谢
